services:
  - type: web
    name: nextjob1-1
    runtime: static
    repo: https://github.com/salim282633-png/NEXTJOB1.1
    branch: main
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    autoDeployTrigger: commit
    pullRequestPreviewsEnabled: true
